### ISSUE TITLE
Ads sound volume

### ISSUE THREAD

**Issue by pozirk** [narenjo/extension-admob#1]
Hey  Narenjo!
Thanks a lot for updated version of extension.

I need ads sound volume control feature, something simple like
`function setVolume(vol:Float)`
I can commit code for AdMob.hx and Android part.
Would you be able to provide iOS part as well?

Also, have you tested version of your extension with Android 8,9+?
There were some problems (app crashes) with original extension.

Thank you!

**Comment by vincent-schirmann** [comment]
Thanks for your kind message (and sorry for the late response).

I'm sorry but we don't plan to to develop more for iOs for now.

Of course if you want to add this feature for Android, don't hesitate to do a pull request.

THank you
